version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libsdl2-2.0
      - run: sudo apt-get install libsdl2-dev
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"